# def run(playwright: Playwright) -> None:
#     browser = playwright.chromium.launch(headless=False)
#     context = browser.new_context()
#     page = context.new_page()
#     page.goto("https://playwright.dev/")
#     page.goto("chrome-error://chromewebdata/")
#     page.locator("html").click()
#     page.goto("http://127.0.0.1:8000/")
#     page.get_by_role("link", name="Sign In").click()
#     page.wait_for_url("http://127.0.0.1:8000/accounts/login/")
#     page.get_by_placeholder("E-mail address").click()
#     page.get_by_placeholder("E-mail address").click()
#     page.get_by_placeholder("E-mail address").fill("admin@rama.com")
#     page.get_by_placeholder("Password").click()
#     page.get_by_placeholder("Password").fill("")
#     page.get_by_role("button", name="Sign In").click()
#     page.wait_for_url("http://127.0.0.1:8000/users/rama/")
#     page.get_by_text("Successfully signed in as rama.").click(click_count=3)
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("button", name="Master Data").click()
#     page.goto("http://127.0.0.1:8000/master/store/")
#     page.get_by_role("link", name="Add").click()
#     page.wait_for_url("http://127.0.0.1:8000/master/store/add/")
#     page.get_by_label("Store Code*").click()
#     page.get_by_label("Store Code*").fill("rama_stores")
#     page.get_by_label("Store Code*").press("Tab")
#     page.get_by_label("Store Name*").fill("Rama Stores")
#     page.get_by_role("button", name="Submit").click()
#     page.wait_for_url("http://127.0.0.1:8000/master/store/?new_code=rama_stores")
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("cell", name="New").click(click_count=3)
#     page.get_by_role("cell", name="Rama Stores").click(click_count=3)
#     page.get_by_role("cell", name="rama_stores").click(click_count=3)
#     page.get_by_role("button", name="Master Data").click()
#     page.goto("http://127.0.0.1:8000/master/product/")
#     page.get_by_role("link", name="Add").click()
#     page.wait_for_url("http://127.0.0.1:8000/master/product/add/")
#     page.get_by_label("Product Code*").click()
#     page.get_by_label("Product Code*").fill("tata_tea_100gms")
#     page.get_by_label("Product Code*").press("Tab")
#     page.get_by_label("Store Name*").fill("Tata Tea 100gms")
#     page.get_by_role("button", name="Submit").click()
#     page.wait_for_url("http://127.0.0.1:8000/master/product/?new_code=tata_tea_100gms")
#     page.get_by_role("button", name="Master Data").click()
#     page.get_by_role("cell", name="tata_tea_100gms").click(click_count=3)
#     page.get_by_role("cell", name="Tata Tea 100gms").dblclick()
#     page.get_by_role("cell", name="Tata Tea 100gms").dblclick()
#     page.get_by_role("cell", name="New").dblclick()
#     page.goto("http://127.0.0.1:8000/master/store/product/")
#     page.get_by_role("link", name="Add").click()
#     page.wait_for_url("http://127.0.0.1:8000/master/store/product/add/")
#     page.get_by_role("combobox", name="Store*").select_option("Rama Stores")
#     page.get_by_placeholder("Type to search...").click()
#     page.get_by_role("link", name="Add Product").click()
#     page.wait_for_url("http://127.0.0.1:8000/master/product/add/")
#     page.get_by_label("Product Code*").click()
#     page.get_by_label("Product Code*").fill("tata_tea_50gms")
#     page.get_by_label("Product Code*").press("Tab")
#     page.get_by_label("Store Name*").fill("T")
#     page.get_by_label("Store Name*").click()
#     page.get_by_label("Store Name*").fill("")
#     page.get_by_label("Store Name*").press("ArrowLeft")
#     page.get_by_label("Store Name*").fill("Tata Tea 50gms")
#     page.locator('form:has-text("Product Code* Store Name* Submit")').get_by_role(
#         "button", name="Submit"
#     ).click()
#     page.wait_for_url("http://127.0.0.1:8000/master/store/product/add/")
#     page.get_by_placeholder("Type to search...").click()
#     page.get_by_placeholder("Type to search...").fill("Tata Tea 50gms")
#     page.get_by_label("Price*").click()
#     page.get_by_label("Price*").fill("34")
#     page.get_by_role("button", name="Submit").click()
#     page.get_by_role("combobox", name="Store*").select_option("Rama Stores")
#     page.get_by_role("button", name="Submit").click()
#     page.wait_for_url(
#         "http://127.0.0.1:8000/master/store/product/?new_code=d2072f3a-e595-4e37-bd90-12b4582e8e4d"
#     )
#     page.get_by_role("cell", name="Rama Stores").click()
#     page.get_by_role("cell", name="Rama Stores").click(click_count=3)
#     page.get_by_role("cell", name="Tata Tea 50gms").dblclick()
#     page.get_by_role("cell", name="34.0").dblclick()
#     page.get_by_role("cell", name="New").dblclick()
#     # ---------------------
#     context.close()
#     browser.close()


# with sync_playwright() as playwright:
#     run(playwright)
