# Generated by Django 4.0 on 2022-10-25 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_productinstore_options'),
        ('shop', '0005_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_in_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='master.productinstore', verbose_name='Product In Store'),
        ),
    ]
