# Generated by Django 4.0 on 2022-10-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_productinstore_options'),
        ('shop', '0006_alter_cartitem_product_in_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_in_store',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_in_store',
            field=models.ManyToManyField(related_name='cart_items', to='master.ProductInStore', verbose_name='Product In Store'),
        ),
    ]
