# Generated by Django 4.0 on 2022-10-28 09:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_productinstore_options'),
        ('users', '0001_initial'),
        ('shop', '0009_remove_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('placed', 'Order Placed'), ('accepted', 'Order Accepted'), ('shipped', 'Order Shipped'), ('delivered', 'Order Delivered'), ('closed', 'Order Closed'), ('cancelled', 'Order Cancelled')], default='placed', max_length=15)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.product')),
            ],
        ),
    ]
