# Generated by Django 4.0 on 2022-10-16 04:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]+$', 'Product code can only be alphanumeric or underscore')], verbose_name='Product Code')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Store Name')),
            ],
            options={
                'ordering': ('code', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]+$', 'Store code can only be alphanumeric or underscore')], verbose_name='Store Code')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Store Name')),
            ],
            options={
                'ordering': ('code', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductInStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.product', to_field='name', verbose_name='Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.store', to_field='name', verbose_name='Store')),
            ],
            options={
                'ordering': ('store', 'product'),
            },
        ),
        migrations.AddConstraint(
            model_name='productinstore',
            constraint=models.UniqueConstraint(fields=('store', 'product'), name='unique_product_in_store'),
        ),
    ]
