# Generated by Django 4.0 on 2022-10-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productinstore',
            constraint=models.UniqueConstraint(fields=('store', 'price'), name='unique_product_and_price'),
        ),
    ]
