# Generated by Django 4.0 on 2022-10-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_productinstore_unique_product_and_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productinstore',
            name='unique_product_and_price',
        ),
    ]
