# Generated by Django 4.0 on 2022-10-08 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_store_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('code', 'name')},
        ),
    ]
