# Generated by Django 4.0 on 2022-10-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_remove_productinstore_unique_product_and_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstore',
            options={'ordering': ('store', 'product'), 'verbose_name': 'Product In Store'},
        ),
    ]
