# Generated by Django 4.0 on 2022-10-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_store_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=15, unique=True, verbose_name='Store Code'),
        ),
    ]
