# Generated by Django 4.0 on 2022-10-13 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]+$', 'Product code can only be alphanumeric or underscore')], verbose_name='Product Code')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Store Name')),
            ],
            options={
                'ordering': ('code', 'name'),
            },
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]+$', 'Store code can only be alphanumeric or underscore')], verbose_name='Store Code'),
        ),
    ]
