# Generated by Django 4.0 on 2022-10-13 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_product_alter_store_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]+$', 'Product code can only be alphanumeric or underscore')], verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Store Name'),
        ),
    ]
