# Generated by Django 4.0 on 2022-10-13 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_alter_product_code_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', 'Store code can only be lower case alphanumeric or underscore')], verbose_name='Store Code'),
        ),
    ]
