# Generated by Django 4.0 on 2022-10-13 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_alter_store_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]+$', 'Store code can only be alphanumeric or underscore')], verbose_name='Store Code'),
        ),
    ]
